services:
  - type: web
    name: laravel-hotel-booking
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: Hotel Booking
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:1t9Ozn2kf7VlJDyvB9Ngx5IfQqE3XjimjSiNkcmRpXQ=
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://laravel-hotel-booking-sto3.onrender.com
      - key: ASSET_URL
        value: https://laravel-hotel-booking-sto3.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-booking-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: hotel-booking-db
    databaseName: hotel_booking_eynx
    user: hotel_user
    plan: free

